name = "tarkov-profit"
main = "src/index.js"
compatibility_date = "2026-08-21"

# Replace with `wrangler kv namespace create PROFIT_KV` output.
[[kv_namespaces]]
binding = "PROFIT_KV"
id = "71d486f57c08492ca86df760dca18ce8"

[vars]
GITHUB_REPO = "TheMooffinMan1/Tarkov-Barters-Crafts"
UPSTREAM_BASE = "https://json.tarkov.dev"
